version: '3.8'
services:
  broker:
    build: ./broker
    ports:
      - "8080:8080"
    volumes:
      - broker-data:/data
  producer:
    build: ./producer
    depends_on:
      - broker
  consumer:
    build: ./consumer
    depends_on:
      - broker
volumes:
  broker-data:
